### ISSUE TITLE
When clicking on create bill many time its will create many payment instead of one payment

### ISSUE THREAD

**Issue by koonwill** [WePays/WePay#103]
![image](https://user-images.githubusercontent.com/93331101/202893852-36c8b48a-96cb-436c-b4d5-20340128343d.png)

**Comment by koonwill** [comment]
Email is bugged too
![image](https://user-images.githubusercontent.com/93331101/202893939-fe669e16-9300-4e6a-9422-dd15cb4c1b6c.png)

**Comment by Tezigudo** [comment]
Fixed
