### ISSUE TITLE
Can I trust in discord login in.

### ISSUE THREAD

**Issue by JiratchayaPhinyodom** [WePays/WePay#112]

**Comment by JiratchayaPhinyodom** [comment]
<img width="1175" alt="Screenshot 2565-11-23 at 09 46 53" src="https://user-images.githubusercontent.com/92837082/203460547-8ec37bb8-74a3-4ebd-bfcd-c37166240ce0.png">
Login with discord.

**Comment by JiratchayaPhinyodom** [comment]
Remove cannot login with github due to duplicate in #74

**Comment by Tezigudo** [comment]
Fixed
