### ISSUE TITLE
Chain id does not has an input box

### ISSUE THREAD

**Issue by oMojiko** [WePays/WePay#118]
In the profile page, it doesn't have the input box on chain id.
![image_2022-11-23_104913438](https://user-images.githubusercontent.com/91252217/203465801-cf608028-6b45-4d44-9401-39e7a1cb1801.png)

**Comment by thanidacwn** [comment]
You don't need to input your chain ID, you can click fetch to get your chain ID If you use the same email in omise.
This detail will show on instruction page, Thank you.
