### ISSUE TITLE
After accept payment but it still not comfirm

### ISSUE THREAD

**Issue by RyukungG** [WePays/WePay#122]
![image](https://user-images.githubusercontent.com/66674210/203468603-a1239d12-7704-4774-ab96-4f34a0e32f04.png)
After I click confirm

![image](https://user-images.githubusercontent.com/66674210/203468689-30519625-da40-4ca4-a99a-ab44423f4929.png)
It don't show any mark

**Comment by RyukungG** [comment]
http://wepays.herokuapp.com/bill/24/

**Comment by koonwill** [comment]
Fix thanks for your information.
