### ISSUE TITLE
When signing in with google it return This app’s request is invalid

### ISSUE THREAD

**Issue by Hamiz5401** [WePays/WePay#128]
Request details: redirect_uri=https://wepays.herokuapp.com/accounts/google/login/callback/

![image](https://user-images.githubusercontent.com/92782075/203691972-15ebe411-b042-47fe-b070-ba907c1c5cd0.png)
![image](https://user-images.githubusercontent.com/92782075/203691996-59c2b1a4-f077-4981-88d4-d3e3ec8e5a21.png)

**Comment by Tezigudo** [comment]
Fixed
