### ISSUE TITLE
Error if I put biggest error that allow in create bill page.

### ISSUE THREAD

**Issue by MarojT** [WePays/WePay#132]
![image](https://user-images.githubusercontent.com/59698469/203930985-73b62d38-e7f9-4982-832b-0f62437e57f6.png)

**Comment by Tezigudo** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/80502090/204023071-d1fd3261-a591-4108-8c3f-c3f880f611ec.png">
I cant replicate it. can you tell me more detail of it?
