### ISSUE TITLE
UX isn't clear.

### ISSUE THREAD

**Issue by JiratchayaPhinyodom** [WePays/WePay#134]
<img width="805" alt="Screenshot 2565-11-25 at 15 55 27" src="https://user-images.githubusercontent.com/92837082/203940858-9a65e600-1646-4cad-aa58-1c5dfed91687.png">
I don't know this is hyperlink.

**Comment by thanidacwn** [comment]
fixed. Thank you.

<img width="1439" alt="Screen Shot 2565-11-26 at 12 00 21" src="https://user-images.githubusercontent.com/92778351/204072977-2d6a0006-0db6-424b-b522-f6728e98ebf2.png">
