### ISSUE TITLE
After created bill and assign all user  it created bill but it also show haven't create menu

### ISSUE THREAD

**Issue by RyukungG** [WePays/WePay#142]
![image](https://user-images.githubusercontent.com/66674210/204144739-a653e5e3-4bb4-41c9-bb4e-30a52c392d9b.png)
![image](https://user-images.githubusercontent.com/66674210/204144858-fc09960e-d72a-4eca-a73f-4cf8189c8c50.png)

**Comment by Tezigudo** [comment]
@RyukungG  can you explain more about this?

**Comment by Tezigudo** [comment]
Cant replicated
