### ISSUE TITLE
On check payment.

### ISSUE THREAD

**Issue by KwangSensei** [WePays/WePay#4]
```
As a user who prepaid.
I want to check whether the bills have been paid yet.  
So that I got the full amount of cashback.
```
If user already prepaid, then bills had been already paid. 
So, if you have prepaid why you want to check whether bills have been paid yet?

**Comment by Tezigudo** [comment]
Bill that we will check mean to check whether the person who must pay money for me has paid or not.
in thai its mean "คนที่ร่วมหารด้วยจ่ายเงินเราหรือยัง(เราออกตังไปก่อน)" xD
